name: Deploy Frontend
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t gyungku/topster-front -f Dockerfile . # Docerfile로 이미지 생성
      - run: docker push gyungku/topster-front # docker hub에 push

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      # elastic beanstalk에 배포
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.AWS_APP_NAME }} # elastic beanstalk의 어플리케이션 이름
          environment_name: ${{ secrets.AWS_APP_ENV_NAME }} # elastic beanstalk의 환경이름
          existing_bucket_name: ${{ secrets.S3_BEANSTALK_BUCKET_NAME }} # s3의 bucket name
          region: ap-northeast-2 # 지역, 위의 지역을 넣자
          version_label: ${{ github.sha }}-${{ github.run_number }}
          use_existing_version_if_available: true
          deployment_package: deploy.zip
