name: Deploy Frontend
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t gyungku/topster-front -f Dockerfile . # Docerfile로 이미지 생성
      - run: docker push gyungku/topster-front # docker hub에 push

      # Elastic Beanstalk에 배포
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.AWS_APP_NAME }}
          environment_name: ${{ secrets.AWS_APP_ENV_NAME }}
          existing_bucket_name: ${{ secrets.S3_BEANSTALK_BUCKET_NAME }}
          region: ap-northeast-2
          use_existing_version_if_available: true