name: Deploy Frontend
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t gyungku/topster-front -f Dockerfile . # Docerfile로 이미지 생성
      - run: docker push gyungku/topster-front # docker hub에 push

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Get current application version
        id: get-version
        run: |
          VERSION=$(aws elasticbeanstalk describe-environments --application-name ${{ secrets.AWS_APP_NAME }} --environment-names ${{ secrets.AWS_APP_ENV_NAME }} --query "Environments[0].VersionLabel" --output text)
          echo "Current version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Redeploy existing version
        run: |
          aws elasticbeanstalk update-environment --application-name ${{ secrets.AWS_APP_NAME }} --environment-name ${{ secrets.AWS_APP_ENV_NAME }} --version-label ${{ steps.get-version.outputs.version }}